export const Actions = {

    // login
    RENDER_LOGIN: "RENDER_LOGIN",
    REQUEST_LOGIN: "REQUEST_LOGIN",

    // register
    REQUEST_REGISTER: "REQUEST_REGISTER",
    RENDER_REGISTER: "RENDER_REGISTER",

    // main
    RENDER_MAIN: 'RENDER_MAIN',
    GET_CARDS: 'GET_CARDS',
    SEND_CARD_ACTION: 'SEND_CARD_ACTION',
    
    // header
    RENDER_HEADER: "RENDER_HEADER",

    // auth
    AUTH_STATE_UPDATED: "AUTH_STATE_UPDATED",
    REQUEST_LOGOUT: "REQUEST_LOGOUT",
}