export const Actions = {

    // login
    RENDER_LOGIN: "RENDER_LOGIN",
    REQUEST_LOGIN: "REQUEST_LOGIN",
    LOGIN_ERROR: "LOGIN_ERROR",

    // register
    REQUEST_REGISTER: "REQUEST_REGISTER",
    RENDER_REGISTER: "RENDER_REGISTER",
    REGISTER_ERROR: "REGISTER_ERROR",

    // main
    RENDER_MAIN: "RENDER_MAIN",
    GET_CARDS: "GET_CARDS",
    SEND_CARD_ACTION: "SEND_CARD_ACTION",
    
    // header
    RENDER_HEADER: "RENDER_HEADER",

    // auth
    AUTH_STATE_UPDATED: "AUTH_STATE_UPDATED",
    REQUEST_LOGOUT: "REQUEST_LOGOUT",
    
    // auth background
    RENDER_AUTH_BACKGROUND: "RENDER_AUTH_BACKGROUND",
    HIDE_AUTH_BACKGROUND: "HIDE_AUTH_BACKGROUND",
}
