export const Actions = {

    // login
    RENDER_LOGIN: "RENDER_LOGIN",
    REQUEST_LOGIN: "REQUEST_LOGIN",
    LOGIN_ERROR: "LOGIN_ERROR",

    // register
    REQUEST_REGISTER: "REQUEST_REGISTER",
    RENDER_REGISTER: "RENDER_REGISTER",
    REGISTER_ERROR: "REGISTER_ERROR",

    // main
    RENDER_MAIN: "RENDER_MAIN",
    GET_CARDS: "GET_CARDS",
    SEND_CARD_ACTION: "SEND_CARD_ACTION",
    
    // home
    RENDER_HOME: "RENDER_HOME",
    
    // header
    RENDER_HEADER: "RENDER_HEADER",

    // auth
    AUTH_STATE_UPDATED: "AUTH_STATE_UPDATED",
    REQUEST_LOGOUT: "REQUEST_LOGOUT",

    // menu
    RENDER_MENU: "RENDER_MENU",
    
    // navigation
    NAVIGATE_TO: "NAVIGATE_TO",
    LOAD_ROUTE: "LOAD_ROUTE",

    // cards
    RENDER_CARDS: "RENDER_CARDS",
    
    // matches
    RENDER_MATCHES: "RENDER_MATCHES",
    RENDER_MATCH_PROFILE: "RENDER_MATCH_PROFILE",
    MATCH_CARD_CLICK: "MATCH_CARD_CLICK",
    
    // chats
    RENDER_CHATS: "RENDER_CHATS",
    
    // my profile
    RENDER_MYCARD: "RENDER_MYCARD",
    UPDATE_PROFILE_FIELD: "UPDATE_PROFILE_FIELD",
    DELETE_PHOTO: "DELETE_PHOTO",
    ADD_PHOTO: "ADD_PHOTO",
    ADD_INTEREST: "ADD_INTEREST",
    DELETE_INTEREST: "DELETE_INTEREST",
    
    // settings
    RENDER_SETTINGS: "RENDER_SETTINGS",
    RENDER_SETTINGS_MENU: "RENDER_SETTINGS_MENU",
    SWITCH_SETTINGS_TAB: "SWITCH_SETTINGS_TAB",
    UPDATE_PROFILE_SETTINGS: "UPDATE_PROFILE_SETTINGS",
    UPDATE_FILTER_SETTINGS: "UPDATE_FILTER_SETTINGS",
    CHANGE_PASSWORD: "CHANGE_PASSWORD",
    DELETE_ACCOUNT: "DELETE_ACCOUNT",
    SETTINGS_ERROR: "SETTINGS_ERROR",
    SETTINGS_RENDER_CONTENT: "SETTINGS_RENDER_CONTENT",
    SETTINGS_CLEAR_ERRORS: "SETTINGS_CLEAR_ERRORS",
    
    // profile menu
    RENDER_PROFILE_MENU: "RENDER_PROFILE_MENU",
    TOGGLE_PROFILE_MENU: "TOGGLE_PROFILE_MENU",
    
    // auth background
    RENDER_AUTH_BACKGROUND: "RENDER_AUTH_BACKGROUND",
    HIDE_AUTH_BACKGROUND: "HIDE_AUTH_BACKGROUND",
    
    // offline banner
    RENDER_OFFLINE_BANNER: "RENDER_OFFLINE_BANNER",
    CONNECTIVITY_CHANGED: "CONNECTIVITY_CHANGED",
}
